services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-container
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC port
    restart: always

  app:
    build: ./app  # Replace this with the path to your app's Dockerfile
    container_name: app-container
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports:
      - "8000:8000"  # Change to your app's port
